language: elixir
matrix:
  include:
    - otp_release: 20.0
      elixir: 1.6
    - otp_release: 20.1
      elixir: 1.6
    - otp_release: 20.2
      elixir: 1.6
    - otp_release: 20.3
      elixir: 1.6
    - otp_release: 21.0
      elixir: 1.6
    - otp_release: 21.1
      elixir: 1.6
    - otp_release: 21.2
      elixir: 1.6
    - otp_release: 21.3
      elixir: 1.6
    - otp_release: 20.0
      elixir: 1.7
    - otp_release: 20.1
      elixir: 1.7
    - otp_release: 20.2
      elixir: 1.7
    - otp_release: 20.3
      elixir: 1.7
    - otp_release: 21.0
      elixir: 1.7
    - otp_release: 21.1
      elixir: 1.7
    - otp_release: 21.2
      elixir: 1.7
    - otp_release: 21.3
      elixir: 1.7
    - otp_release: 21.0
      elixir: 1.8
    - otp_release: 21.1
      elixir: 1.8
    - otp_release: 21.2
      elixir: 1.8
    - otp_release: 21.3
      elixir: 1.8
install:
  - mix local.hex --force
  - mix local.rebar
  - mix deps.get
script:
  - mix test
